### PR TITLE
Fix yarn bootstrap after babylon renaming

### PR DESCRIPTION
**Pull request by alexzherdev**

### CODE REVIEW

**Comment by hzoo** [comment]
Deploy preview for *babel-new* ready!

Built with commit de169a4533bcb576dad1f30db0c954a1ce5fbfb6

https://deploy-preview-1674--babel-new.netlify.com

**Comment by xtuc** [comment]
Have you tried to run scripts/download-readmes.js?

**Comment by alexzherdev** [comment]
AFAICT it's run first thing as part of the `bootstrap` script:
```
"bootstrap": "npm run bootstrap:readmes && npm run bootstrap:sponsors && npm run build",
"bootstrap:readmes": "node ./scripts/download-readmes.js",
```
BTW I'm still seeing `babylon` in the sidebar, not sure what else needs to be done.

**Comment by xtuc** [comment]
Ok. I'm seeing the Babylon in the preview as well. I'm on mobile but maybe there's still an occurrence in the code.

**Comment by microbouji** [comment]
I think the Babylon page you're seeing is for the 6.x version. It's coming from the versioned sidebar [here](https://github.com/babel/website/blob/master/website/versioned_sidebars/version-6.x-sidebars.json) as it should.

This change looks good to me and can be seen at the ["next"](https://deploy-preview-1674--babel-new.netlify.com/docs/en/next/babel-parser.html) version of the docs.

**Comment by hzoo** [comment]
Would change this in the gitignore until we move all the docs to the repo? https://github.com/babel/website/blob/7b02d339f663236bca34fa79ba7254648846a315/.gitignore#L48

**Comment by alexzherdev** [comment]
@hzoo done! Does this need to be re-approved?

**Pull request merged**
