### PR TITLE
add new sponsors, patreon, update links

### PR DESCRIPTION
**Pull request by hzoo**

### CODE REVIEW

**Comment by hzoo** [comment]
Deploy preview for *babel-old* ready!

Built with commit ea882752b079a712cf11da3fc50648dce3024dfc

https://deploy-preview-1616--babel-old.netlify.com

**Comment by hzoo** [comment]
Deploy preview for *babel-old* ready!

Built with commit b2b0c91e11558978dd7a7fa879c3e1deb5b01286

https://deploy-preview-1616--babel-old.netlify.com

**Comment by hzoo** [comment]
Ah it was causing a JS error @xtuc so I did https://github.com/babel/website/pull/1616/commits/712bbddb3ca4239358260cc994761c851c06dac7

**Comment by xtuc** [comment]
omg my bad! Really sorry about that, let's pretend it was part of the joke.

**Pull request merged**
