### PR TITLE
Babel song

### PR DESCRIPTION
**Pull request by xtuc**

### CODE REVIEW

**Comment by hzoo** [comment]
Deploy preview for *babel-old* ready!

Built with commit 09e725a8b8102f74cf08314f147cded8a8dc74f4

https://deploy-preview-1615--babel-old.netlify.com

**Comment by hzoo** [comment]
cc @sw-yx

FYI: we could just revert the PR the next day to switch back

**Comment by hzoo** [comment]
Feel free to update/PR if it could be better

**Comment by hzoo** [comment]
The users part is broken from this I think

**Comment by sw-yx** [comment]
haha that was fun :) thanks for getting in touch

**Pull request merged**
