### PR TITLE
Update(data,static): name, url, logo, and svg for Ormica

### PR DESCRIPTION
**Pull request by killshot13**
Hello, I am a developer at Ormica, a real estate investment firm in Miami, FL, and we would like to add our company details to your wall of users.

As the CTO of the company, I am authorized to represent Ormica, and I can also confirm we are using Babel as a key part of our technology stack, so here is my shoutout. Feel free to use it as you please. :)

>"Babel is awesome because it allows us to experiment with the latest features and updates in JavaScript and develop cutting-edge React web apps while retaining acceptable UX across older browser versions!"

If you need any further information or proof of identity, please contact me via email at my [domain address](mailto:michael@ormica.com).

### CODE REVIEW

**Review by existentialism — APPROVED** [review]

**Comment by fedeci** [comment]
@killshot13 I can't access the website due to Cloudflare error 1020, is it normal?

**Comment by existentialism** [comment]
@fedeci works for me!

**Comment by fedeci** [comment]
Might it be my location? Tried on different browsers and no one is working🤔

**Comment by killshot13** [comment]
My apologies, it was a misconfigured geographical rate-limiter setting in Cloudflare. You should be able to see it now @fedeci.

**Comment by fedeci** [comment]
Now I can!

**Pull request merged**
