### PR TITLE
Create 2017-07-12-zero-config-with-babel-macros.md

### PR DESCRIPTION
**Pull request by kentcdodds**
Start work on #1275

Just to get things going

### CODE REVIEW

**Comment by hzoo** [comment]
love it already

I was going to write a blog post about Babel the other day and it would just say `We need help`

**Comment by existentialism** [comment]
@kentcdodds yay! I was scared you forgot about us :)

**Comment by kentcdodds** [comment]
I just published 1.0.0 of `babel-macros` :)

**Comment by kentcdodds** [comment]
Thanks @ericclemmons! Maybe you missed the paragraph where I list pretty much every existing macro, and then the one later where I express a hope that more libraries will implement macros... Can I make it more clear?

**Comment by kentcdodds** [comment]
I'm guessing the build failures are unrelated to my changes. Please let me know what I need to update about this PR if anything :)

**Comment by hzoo** [comment]
I think we should probably mention at the top or somewhere we don't intend for macros to be used for syntax transforms (the main purpose of Babel, to transform latest js into older js) but for other kinds of code transformation. Might be related to @ericclemmons' question. It's not really that much of a thing for most users - just a better ux for lib authors that are doing "some" kinds of code transformation.

**Comment by kentcdodds** [comment]
I end the blog post with: 

> `babel-macros` takes a slightly different approach however. While macros have often been associated with defining new syntax for a language, that's not the goal of `babel-macros` at all. In the case of `babel-macros` it's more about code transformations.

I'm not sure of a good place to put that other than where it is... Ideas?

**Comment by hzoo** [comment]
Yeah I saw, I'd like it at the top in some form if not just to say Babel is used for more things than just esnext, and Babel macros helps with that or something?

**Comment by kentcdodds** [comment]
Alrighty, I [updated some of the text](https://github.com/babel/website/pull/1277/commits/9d859a5217a8702f51e8dde032d2621e44ee9b4e). I think that should work.

**Comment by hzoo** [comment]
I think this is good, we can land 🙂

maybe we could have a section that explains what you wouldn't use babel-macros for though, so other community plugins/users have a better idea why/why not use babel-macro

**Comment by existentialism** [comment]
@kentcdodds thanks so much!

**Comment by kentcdodds** [comment]
Thank you @existentialism and @hzoo! 👏

**Pull request merged**
