### PR TITLE
Add 7.8 in version

### PR DESCRIPTION
**Pull request by rajasekarm**
Updated latest version.

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Thanks!
We actually have a script in the `website/` package which bumps the version and generates the versioned docs: `cd website && npm run version`.

**Comment by existentialism** [comment]
FWIW, I would have prefer we ran the script instead of landing this... as it's nice to have _just_ the files that changed from version to version instead of every doc getting added to the `version-7.8.0` folder (like https://github.com/babel/website/tree/master/website/versioned_docs/version-7.7.0).

**Comment by nicolo-ribaudo** [comment]
The script copied every file because in https://github.com/babel/website/pull/2150 I modified every doc.
I should work on backporting the `### With a configuration file (Recommended)` changes and then re-run the script to clean up the 7.8.0 folder.

**Comment by existentialism** [comment]
Ahh... yeah, not critical, just a nicety.

**Pull request merged**
