### PR TITLE
fix : "Get browser-compatible JavaScript out" Scrollbar Not working

### PR DESCRIPTION
**Pull request by prajyot004**
### Description
Fixed the issue of horizontal scrolling in homepage mini editor. Horizontal scroll was not working. I have linked the both videos of after and before fix.

Fixes : #2855

Before fix 

https://github.com/babel/website/assets/75519731/f3f602ca-b84e-4aff-8d54-4b60f42c5f81

After fix

https://github.com/babel/website/assets/75519731/65cabac9-6864-4612-96ab-7a1a57cf1e0d

### CODE REVIEW

**Review by nicolo-ribaudo — COMMENTED** [review]
Thank you! Would it be possible to fix this in a way that makes the scrollbar visible only when it's actually needed?

**Comment by prajyot004** [comment]
I'll try to do that

**Comment by prajyot004** [comment]
@nicolo-ribaudo I looked for solution but there is only two ways either we need to keep the output window selectable not editable OR always keep the horizontalscrollbars visible. And on top of it we are keeping the error message window there only we are just change its opacity to 1 when error occurs the pace is  still occupied by error div  so it is making conflicts between scrollbar and error div.
As of now "ace editor" does not provide the property to focus on the scroll bar so there are only two possible solutions are there.

**Comment by JLHwung** [comment]
Thank you for your PR.

This issue has been fixed in https://github.com/babel/website/pull/2750. We enabled the line wrapping for the landing page REPL so there won't be a horizontal scroll bar at all.

**Pull request closed without merging**
