### PR TITLE
New proposed changes for REPL

### PR DESCRIPTION
**Pull request by rajzshkr**
For the proposed changed for new REPL, Please check [this comment](https://github.com/babel/website/pull/1441#discussion_r147421106).

### CODE REVIEW

**Comment by rajzshkr** [comment]
Ping @Daniel15 @bvaughn

**Comment by bvaughn** [comment]
CI is complaining about lint/formatting errors

https://travis-ci.org/babel/website/builds/295301202?utm_source=github_status&utm_medium=notification

**Comment by rajzshkr** [comment]
Fixed all the lint issues. But the build is failing because of **The command "./scripts/download-readmes.js" exited with 1.**

**Comment by rajzshkr** [comment]
ping @bvaughn

**Comment by bvaughn** [comment]
Hey @rajzshkr 😄 I'll check this when I can. It's in my inbox. No need to re-ping. 👍

**Comment by bvaughn** [comment]
Sorry, I've been on the road traveling. It's late here (in the UK) and I'm tired, but at a glance- this looks solid. I didn't test it though, which I'd need to before merging.

**Pull request closed without merging**
