### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by likerRr**

### CODE REVIEW

**Comment by hzoo** [comment]
Thank you!

**Comment by likerRr** [comment]
@hzoo I'm not sure why, but for some reason links are not parsed on live site https://babeljs.io/docs/en/babel-preset-env . Can you check please?

**Comment by microbouji** [comment]
@likerRr it's good your changes are live in the "next" version here: https://babeljs.io/docs/en/next/babel-preset-env

If you want to add the links to the v6 page as well, the doc is here: https://github.com/babel/website/blob/master/website/versioned_docs/version-6.x/preset-env.md

**Comment by likerRr** [comment]
@microbouji oh, thanks for explanation

**Comment by likerRr** [comment]
Pushed fixes to v6 #1751

**Pull request merged**
