### PR TITLE
docusaurus@1.0.11

### LINKED ISSUE #1614: Issue with markdown headings
http://new.babeljs.io/docs/en/next/v7-migration.html

image

### PR DESCRIPTION
**Pull request by microbouji**
Fixes #1614 

Looks like this release also added warnings for invalid header fields in the front matter of docs, so I guess we'll have to remove them as well.

### CODE REVIEW

**Comment by hzoo** [comment]
Deploy preview for *babel-new* ready!

Built with commit b3359469a7b79ce76241b3f90f96bb6e1171f166

https://deploy-preview-1624--babel-new.netlify.com

**Comment by hzoo** [comment]
great

**Comment by JoelMarcey** [comment]
@microbouji Hi. Will the header warnings be an issue for you? If so, we can add a suppression config option if needed.

**Comment by microbouji** [comment]
@JoelMarcey yeah we currently have comments and empty lines in there and it's sending a warning for each. I'll look into it some more to see what we can and can't remove and will get back to you with suggestions.

**Comment by JoelMarcey** [comment]
Sounds good. I am willing to be super flexible on the implementation of this. I can ignore empty lines, comments and/or have a suppression option. Just let me know.

**Pull request merged**
