### PR TITLE
Make docs nav sidebar sticky, add on-page nav

### LINKED ISSUE #1536: New Site: fixed sidebar
Would like the sidebar for the new docs to be fixed like in https://reactjs.org/docs/hello-world.html and vue https://vuejs.org/v2/guide/

Not a blocker to switch but something we should do later?

### PR DESCRIPTION
**Pull request by microbouji**
commited with no-verify as I was getting some flow errors from the repl?

This fixes #1536 

I've made no visual changes to the docs sidebar.

Idea for the future: could make doc categories in the left sidebar collapsible and/or add pjax to save scroll location like https://reasonml.github.io/reason-react/docs/en/installation.html

### CODE REVIEW

**Comment by hzoo** [comment]
Deploy preview for *babel-new* ready!

Built with commit b666395ed399b0685e35c3569d9fa984fe74f9a0

https://deploy-preview-1582--babel-new.netlify.com

**Comment by hzoo** [comment]
Really cool!

**Comment by JoelMarcey** [comment]
I wonder if this could be upstreamed as a config option to the Docusaurus core? Folks have been asking for something like this.

**Comment by xtuc** [comment]
@JoelMarcey Yeah that would be better and I guess that's a common use case. Thanks!

**Comment by existentialism** [comment]
Yeah, I second upstreaming this to Docusaurus!

**Comment by JoelMarcey** [comment]
An upstream PR is being worked on by @microbouji. 🎉 

https://github.com/facebook/Docusaurus/pull/475

**Comment by microbouji** [comment]
Yep, looks like this will be part of docusaurus soon :tada:.  Thanks for quick reviews @JoelMarcey!

**Comment by existentialism** [comment]
@microbouji awesome, thanks!

**Pull request closed without merging**
