### PR TITLE
New User: Coupa

### PR DESCRIPTION
**Pull request by KheeWong**
Coupa developers ❤️ Babel!! You all rock! 🎸 , thank you for the unseen hard work.

### CODE REVIEW

**Comment by xtuc** [comment]
We are currently refactoring the website. Do you mind if I change the target to the new website, that means that you'll need to wait for a bit until your name will be listed publicly.

**Comment by KheeWong** [comment]
I don't mind, thanks.

**Comment by hzoo** [comment]
Ok I just changed docusaurus to master so it's ok again haha (but different folders now 😛 )

**Comment by KheeWong** [comment]
No problem 👌  . I am going to close this PR and create another PR with the new site structure.

**Pull request closed without merging**
