### PR TITLE
fix(externalPlugins): make sure the input is focusing correctly in Safari

### LINKED ISSUE #1610: "Only official Plugins" checkbox is toggled when clicking in plugin name field in Safari
babel-website-bug

### Steps to Reproduce

1. Go to the [repl](https://babeljs.io/repl/) in Safari on macOS.
2. Toggle open the "Plugins" section.
3. Click on the field with placeholder "Type the plugin name".

### Expected

The field should receive input focus.

### Actual

The field briefly receives input focus but the "Only official Plugins" checkbox toggles its state and the plugin name field loses input focus, making it impossible to focus with the mouse. It can still be focused with the keyboard.

### Commentary

This is likely due to the weird HTML structure of this section of the sidebar. The plugin name `<input>` is inside a `<label>` which also contains another `<label>` which contains the checkbox `<input>`. I think this structure may not be valid, which means that behavior may be somewhat undefined.

```html
<label class="css-1ialo1l">
    <div class="css-13l6cwb">
        <label class="css-1h259tg css-1xo3mso">
            <input type="checkbox" class="css-1yr5jo5" value="on" />Only official Plugins
        </label>
        <input
                type="text"
                placeholder="Type the plugin name"
                value=""
                class="css-1qjy9c4 css-qnx592"
        />
        <div class="ais-Hits__root">
            <label class="css-13o7eu2">
                <input type="checkbox" class="css-1yr5jo5" value="on" />transform-es2015-modules-commonjs
            </label>
            <label class="css-13o7eu2">
                <input type="checkbox" class="css-1yr5jo5" value="on" />transform-strict-mode
            </label>
            <label class="css-13o7eu2">
                <input type="checkbox" class="css-1yr5jo5" value="on" />transform-regenerator
            </label>
            <label class="css-13o7eu2">
                <input type="checkbox" class="css-1yr5jo5" value="on" />transform-es2015-parameters
            </label>
            <label class="css-13o7eu2">
                <input type="checkbox" class="css-1yr5jo5" value="on" />transform-es2015-block-scoping
            </label>
            <label class="css-13o7eu2">
                <input type="checkbox" class="css-1yr5jo5" value="on" />transform-es2015-destructuring
            </label>
            <label class="css-13o7eu2">
                <input type="checkbox" class="css-1yr5jo5" value="on" />transform-es2015-function-name
            </label>
            <label class="css-13o7eu2">
                <input type="checkbox" class="css-1yr5jo5" value="on" />transform-es2015-unicode-regex
            </label>
            <label class="css-13o7eu2">
                <input type="checkbox" class="css-1yr5jo5" value="on" />transform-es2015-sticky-regex
            </label>
            <label class="css-13o7eu2">
                <input type="checkbox" class="css-1yr5jo5" value="on" />transform-es2015-spread
            </label>
        </div>
    </div>
    <div />
</label>
```

### PR DESCRIPTION
**Pull request by Haroenv**
I didn't test this in a browser, but will use the deploy preview. 

fixes #1610

Also ran this file through prettier on their repl and it seems to be a little bit different than what it originally was formatted as, I can revert those lines if needed

### CODE REVIEW

**Comment by hzoo** [comment]
Deploy preview for *babel-new* ready!

Built with commit 9f08afcf68f20a92660ab24769c76f95141cfda8

https://deploy-preview-1612--babel-new.netlify.com

**Comment by xtuc** [comment]
@eventualbuddha could you please try here https://deploy-preview-1612--babel-new.netlify.com/repl?

Thanks for your PR @Haroenv :+1:

**Comment by Haroenv** [comment]
PR seems to work in Safari for me

**Comment by hzoo** [comment]
Deploy preview for *babel-new* ready!

Built with commit 9bcfbd02d1d622be37cdc4002ecea1ae68a03ea3

https://deploy-preview-1612--babel-new.netlify.com

**Comment by Haroenv** [comment]
Is this PR only for the new website, or will it automatically get applied to the old one too?

**Comment by existentialism** [comment]
@Haroenv you'll need to send a fix to the `old-site` branch as well

**Pull request merged**
