### PR TITLE
Refactored sidebar to use accordions

### LINKED ISSUE #1347: Convert REPL sidebar to accordion view
It's already a bit cramped and this will only get worse once issues like #858 and #1292 are added.

I propose a design similar to what CodeSandbox.io uses:
screen shot 2017-08-27 at 4 25 26 pm

It should provide us lots of room to grow.

### PR DESCRIPTION
**Pull request by bvaughn**
Resolves #1347 

**TODO**:
* Lift accordion expanded state up so that collapsing/expanding the sidebar doesn't reset which accordions are expanded.
* Don't let `textarea` in "Env" section cause the nav size to change when opened.

# Screenshot: Resizing
sidebar-accordion-resized

# Screenshot: Large
sidebar-accordion-large

# Screenshot: Medium
sidebar-accordion-medium

# Screenshot: Small
sidebar-accordion-small

### CODE REVIEW

**Comment by xtuc** [comment]
:heart_eyes:

**Comment by existentialism** [comment]
In a later PR, we should maybe rethink the sidebar toggling... it is now a bit high on arrow density (and when it overflows, the scrollbar makes it look not-so-great) :)

image

Also, not entirely sold on the utility of the collapsing in the medium state... but I suppose it doesn't really _hurt_ anything for now .We'll need to revisit the layout in the very near future anyway when we bolt on loading plugins from external. I can crystal ball seeing the defaults (Presets + Env) both being in the center column and the right area being the "load your custom stuff from npm".

**Comment by bvaughn** [comment]
Oh, whoops. There were still 2 TODO items listed in the description. Sorry for being unclear! I'll do a quick follow-up PR.

**Comment by existentialism** [comment]
Haha, @xtuc was quick on the trigger :)

No worries tho!

**Comment by xtuc** [comment]
Oh sorry :disappointed_relieved:

**Comment by bvaughn** [comment]
No it's my fault! I should have put a "WIP" in the summary tag 😄  I pushed this PR earlier than I normally would have b'c I wanted to use Netlify to test on different devices 😁  It's just too convenient.

**Comment by xtuc** [comment]
Ok, does the preview still work even after the PR was merged?

**Comment by bvaughn** [comment]
Yeah. We're good. 😄  #1357 is a quick follow-up.

I'll think a little more about what Brian said, regarding whether we need the collapsing feature still. It would certainly simplify the code to get rid of it, but I worry the vertical menu would take up too much space on smaller devices.

**Pull request merged**
