### PR TITLE
docusaurus@1.3.1

### LINKED ISSUE #1693: Broken PREVIOUS/NEXT links for polyfill and register on runtime generators page
On this page, the PREVIOUS/NEXT links for BABEL-POLYFILL and BABEL-REGISTER are broken (404 errors).  I'm referring to the two links at the bottom of the page, not the ones in the sidebar(s):

https://babeljs.io/docs/en/babel-plugin-transform-runtime/

Here are the URLs for the broken links:

https://babeljs.io/docs/en/babel-plugin-transform-runtime/babel-polyfill.html
https://babeljs.io/docs/en/babel-plugin-transform-runtime/babel-register.html

Here the links for those same destination pages taken from the sidebar equivalent links, which do work:

https://babeljs.io/docs/en/babel-polyfill.html
https://babeljs.io/docs/en/babel-register.html

It looks like there is some bad template expansion code somewhere that is adding the _current page name_, "babel-plugin-transform" in this instance, to the PREVIOUS/NEXT links in some cases.  Therefore, it may be happening on a lot more pages than this one.

### PR DESCRIPTION
**Pull request by microbouji**
Fixes #1693 

### CSS Changes!!!
This docusaurus release had css changes and I took this moment to clean up our own css a bit.

As an experiment I started by removing all of our custom css to put them back one by one. But I ended up liking the dark menu a lot so I left it like that. Let me know what you think -- should just take one small commit here to change it back to yellow again.

Basically the dark menu and footer are the only visual changes I meant to do. Anything else might be something I missed, small changes that don't make a difference either way, or most likely things that are now included in the docusaurus core so I'm removing them from our side (the diff on `babel.css` might look messy but it's mostly just things I took out or changed for this reason).

### CODE REVIEW

**Comment by hzoo** [comment]
Deploy preview for *babel-new* ready!

Built with commit 344c94e1a86822983750edab10c34d198f0bb5d8

https://deploy-preview-1708--babel-new.netlify.com

**Comment by existentialism** [comment]
Small nit, but the search box alignment seems to have changed?

image

vs.

image

**Comment by existentialism** [comment]
Search box icon needs some margin (easy way to repro is to set chrome dev tools to iPad portrait):

image

**Comment by existentialism** [comment]
Should we reduce the amount of margin here:

image

For ref, here's before:

image

**Comment by existentialism** [comment]
Is always-on scrollbar (scroll vs auto) on the blog sidebar intentional?

image

**Comment by microbouji** [comment]
Wow thank you @existentialism! I fixed these, except for the blog scrollbar. That is strangely coming from some old version of docusaurus. The latest version has it correctly set to auto (https://github.com/facebook/Docusaurus/blob/master/lib/static/css/main.css#L1570) but I think due to some caching issue it's generating an old main.css.

I also moved the home styles to `index.css`.

**Comment by microbouji** [comment]
Turns out that was just changed 3 days ago in https://github.com/facebook/Docusaurus/commit/e4b9b9861b0374790b19f3f84f51ee34f8710f68 and it's not released to npm yet.

**Comment by JoelMarcey** [comment]
We are going to try to get a 1.3.1 release out tonight or tomorrow.

**Comment by microbouji** [comment]
@JoelMarcey all good. Also, I think the search box changes in here https://github.com/babel/website/pull/1708/commits/d47457e24c6029eca058b26a895fc259ee69363b should be upstreamed.

**Comment by existentialism** [comment]
👍

**Pull request merged**
