### PR TITLE
New User: YSI Corporation

### PR DESCRIPTION
**Pull request by ysidev**
Added a image an text to user and images folder.

### CODE REVIEW

**Comment by ysidev** [comment]
We love Babel, it's a great job.

**Comment by existentialism** [comment]
@ysidev sorry for the delay! curious, is there any way you can give us a svg that isn't an embedded png? Also, can you please size it to 500x200? thanks.

**Comment by ysidev** [comment]
@existentialism Sure, link as follow. https://res.cloudinary.com/ysicorp/image/upload/v1507634974/ysicorp-500x200_a1yfpv.svg

Thanks.

**Comment by xtuc** [comment]
This PR is too old. Please @ysidev re-open it with your updated SVG if you want to be on the website.

**Pull request closed without merging**
