### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Message from automatic PR by @imgbot (as seen in https://github.com/MichaelDeBoey/website/pull/94):

> ## Beep boop. Your images are optimized!
> 
> Your image file size has been reduced by **15%** 🎉
> 
> <details>
> <summary>
> Details
> </summary>
> 
> | File | Before | After | Percent reduction |
> |:--|:--|:--|:--|
> | /website/blog/assets/2016-12-07-the-state-of-babel/eslint.png | 172.50kb | 100.10kb | 41.97% |
> | /website/static/img/sponsors/tidelift.png | 7.36kb | 4.89kb | 33.62% |
> | /website/static/img/sponsors/vpnranks.png | 2.14kb | 1.52kb | 28.93% |
> | /website/blog/assets/2017-08-16-gsoc-karl-1/debugger-cropped.png | 109.66kb | 81.31kb | 25.85% |
> | /website/blog/assets/2017-08-16-gsoc-karl-1/question.png | 18.75kb | 15.43kb | 17.70% |
> | /website/blog/assets/2017-08-16-gsoc-karl-1/babel-test.png | 35.19kb | 29.03kb | 17.50% |
> | /website/static/img/users/adpushup.png | 13.19kb | 11.07kb | 16.07% |
> | /website/blog/assets/2017-08-16-gsoc-karl-1/update.png | 34.32kb | 29.22kb | 14.86% |
> | /website/blog/assets/2017-08-16-gsoc-karl-1/time-zone-list.png | 62.76kb | 54.46kb | 13.23% |
> | /website/static/img/user.svg | 1.10kb | 0.95kb | 13.16% |
> | /website/blog/assets/2017-08-16-gsoc-karl-1/world-map.png | 399.03kb | 347.71kb | 12.86% |
> | /website/blog/assets/2017-08-16-gsoc-karl-1/chromium-task-manager.png | 28.55kb | 25.98kb | 9.03% |
> | /website/static/img/users/rubrik.svg | 32.19kb | 30.12kb | 6.42% |
> | /website/static/img/favicon.png | 2.20kb | 2.09kb | 4.84% |
> | /website/static/img/users/bitmidi.svg | 1.48kb | 1.43kb | 3.75% |
> | /website/static/img/users/ilovecoding.svg | 12.42kb | 12.18kb | 1.94% |
> | /website/static/img/sponsors/bestvpn.png | 41.37kb | 40.80kb | 1.36% |
> | /website/static/img/users/refinery29.svg | 1.96kb | 1.93kb | 1.35% |
> | /website/static/img/users/wave.svg | 4.23kb | 4.18kb | 1.25% |
> | /website/static/img/users/taskade-logo.svg | 29.78kb | 29.42kb | 1.19% |
> | /website/static/img/users/skype-logo.svg | 2.09kb | 2.07kb | 1.07% |
> | /website/static/img/users/rtbf.svg | 2.14kb | 2.13kb | 0.68% |
> | /website/static/img/users/zestyio.svg | 2.83kb | 2.81kb | 0.48% |
> | /website/static/img/users/exante.svg | 0.86kb | 0.86kb | 0.34% |
> | /website/static/img/users/zimp.svg | 6.74kb | 6.71kb | 0.33% |
> | /website/static/img/users/directlyrics.svg | 3.44kb | 3.43kb | 0.28% |
> | /website/static/img/users/evocompany.svg | 4.18kb | 4.17kb | 0.28% |
> | /website/static/img/users/hootsuite.svg | 2.50kb | 2.49kb | 0.27% |
> | /website/static/img/users/hijup.svg | 1.46kb | 1.45kb | 0.27% |
> | /website/static/img/users/n26.svg | 1.19kb | 1.19kb | 0.25% |
> | /website/static/img/users/hux.svg | 0.51kb | 0.51kb | 0.19% |
> | /website/static/img/users/shelfio.svg | 3.09kb | 3.08kb | 0.19% |
> | /website/static/img/users/naustudio.svg | 8.25kb | 8.24kb | 0.15% |
> | /website/static/img/icons/twitter.svg | 0.67kb | 0.67kb | 0.15% |
> | /website/static/img/users/rentomojo.svg | 2.46kb | 2.45kb | 0.12% |
> | /website/static/img/users/hashnode.svg | 3.42kb | 3.42kb | 0.11% |
> | /website/static/img/icons/github.svg | 0.90kb | 0.90kb | 0.11% |
> | /website/static/img/users/lesalon.svg | 2.15kb | 2.14kb | 0.09% |
> | /website/static/img/users/uncovertruth.svg | 7.79kb | 7.78kb | 0.09% |
> | /website/static/img/icons/slack.svg | 1.13kb | 1.12kb | 0.09% |
> | /website/static/img/users/bitovi-logo.svg | 1.80kb | 1.80kb | 0.05% |
> | /website/static/img/users/paralect.svg | 1.94kb | 1.94kb | 0.05% |
> | /website/static/img/users/aha.svg | 2.02kb | 2.02kb | 0.05% |
> | /website/static/img/users/transloadit.svg | 6.83kb | 6.83kb | 0.04% |
> | /website/static/img/users/workandco.svg | 2.35kb | 2.35kb | 0.04% |
> | /website/static/img/users/seatgeek.svg | 2.39kb | 2.39kb | 0.04% |
> | /website/static/img/users/justeat.svg | 2.45kb | 2.45kb | 0.04% |
> | /website/static/img/users/pixiv.svg | 2.59kb | 2.59kb | 0.04% |
> | /website/static/img/users/streamroot.svg | 8.14kb | 8.13kb | 0.04% |
> | /website/static/img/users/9tech-logo.svg | 2.92kb | 2.92kb | 0.03% |
> | /website/static/img/users/umanlife.svg | 3.06kb | 3.06kb | 0.03% |
> | /website/static/img/users/namely.svg | 3.28kb | 3.28kb | 0.03% |
> | /website/static/img/users/microsoft.svg | 3.40kb | 3.40kb | 0.03% |
> | /website/static/img/users/quicksearch.svg | 44.64kb | 44.63kb | 0.03% |
> | /website/static/img/users/jobtalk.svg | 7.49kb | 7.49kb | 0.03% |
> | /website/static/img/users/yeti.svg | 4.46kb | 4.46kb | 0.02% |
> | /website/static/img/users/hooroo.svg | 4.93kb | 4.93kb | 0.02% |
> | /website/static/img/users/nytimes.svg | 5.54kb | 5.54kb | 0.02% |
> | /website/static/img/users/bevry.svg | 6.58kb | 6.58kb | 0.01% |
> | /website/static/img/users/broadbanduk.svg | 6.75kb | 6.75kb | 0.01% |
> | /website/static/img/users/justwatch.svg | 7.19kb | 7.19kb | 0.01% |
> | /website/static/img/users/holidaycheck.svg | 13.11kb | 13.11kb | 0.01% |
> | /website/static/img/users/teachoo.svg | 20.58kb | 20.58kb | 0.00% |
> | /website/static/img/babel.svg | 32.01kb | 32.01kb | 0.00% |
> | | | | |
> | **Total :** | **1,264.44kb** | **1,077.90kb** | **14.75%** |
> </details>
> 
> ---
> 
> **Black Lives Matter** | [💰 donate](https://blm-bookmarks.carrd.co/#donate) | [🎓 learn](https://blm-bookmarks.carrd.co/#learn) | [✍🏾 sign](https://blm-bookmarks.carrd.co/#sign)
> 
> [📝 docs](https://imgbot.net/docs) | [:octocat: repo](https://github.com/dabutvin/ImgBot) | [🙋🏾 issues](https://github.com/dabutvin/ImgBot/issues) | [🏅 swag](https://goo.gl/forms/1GX7wlhGEX8nkhGO2) | [🏪 marketplace](https://github.com/marketplace/imgbot)

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
If you want, you can install https://imgbot.net in this repo (or in the full organization).
It will automatically send PRs for image optimization 🙂

**Comment by xtuc** [comment]
SVG should already have been optimized and we can enable Cloudflare's png/jpeg optimization on the fly, no need to do it here.

**Comment by MichaelDeBoey** [comment]
@xtuc This will make the repo smaller too.

**Comment by MichaelDeBoey** [comment]
Ping @xtuc

**Comment by nicolo-ribaudo** [comment]
The size of the svg files still seems the same?

**Comment by MichaelDeBoey** [comment]
@nicolo-ribaudo Don't know how imgbot handles svg files. The only thing I know is that they're using [`svgo`](https://github.com/svg/svgo) to handle the optimization.

**Comment by MichaelDeBoey** [comment]
Ping @nicolo-ribaudo @xtuc

**Comment by nicolo-ribaudo** [comment]
I would be ok with optimizing binary images, but please revert the changes to `svg`s since it doesn't seem to give any benefit.

**Comment by MichaelDeBoey** [comment]
@nicolo-ribaudo This was don automatically by the bot. I just created the PR.

**Pull request closed without merging**
