### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by AnYiLin**
ES6++

### CODE REVIEW

**Comment by JLHwung** [comment]
Can you clarify the motivation of this PR? `(n) => n + 1` and `n => n + 1` is equivalent.

**Comment by AnYiLin** [comment]
The latter can better reflect the characteristics of es6, I think.

**Comment by JLHwung** [comment]
We use [prettier](https://prettier.io/docs/en/options.html#arrow-function-parentheses) to enforce a consistent code style among docs. The option `arrowParens` instructs `prettier` whether an arrow paren should be avoided if possible. The default value was changed from `avoid` (`n => n + 1`) to `always` (`(n) => n + 1`) in v2.0.0. Here is the rationale:

> At first glance, avoiding parentheses may look like a better choice because of less visual noise. However, when Prettier removes parentheses, it becomes harder to add type annotations, extra arguments or default values as well as making other changes. Consistent use of parentheses provides a better developer experience when editing real codebases, which justifies the default value for the option.

Although I am not going to accept this PR, thanks for contributing to Babel docs anyway!

**Comment by AnYiLin** [comment]
> We use [prettier](https://prettier.io/docs/en/options.html#arrow-function-parentheses) to enforce a consistent code style among docs. The option `arrowParens` instructs `prettier` whether an arrow paren should be avoided if possible. The default value was changed from `avoid` (`n => n + 1`) to `always` (`(n) => n + 1`) in v2.0.0. Here is the rationale:
> 
> > At first glance, avoiding parentheses may look like a better choice because of less visual noise. However, when Prettier removes parentheses, it becomes harder to add type annotations, extra arguments or default values as well as making other changes. Consistent use of parentheses provides a better developer experience when editing real codebases, which justifies the default value for the option.
> 
> Although I am not going to accept this PR, thanks for contributing to Babel docs anyway!

I got it. Thanks.

**Pull request closed without merging**
