### PR TITLE
Move compilation to a worker

### PR DESCRIPTION
**Pull request by boopathi**

### CODE REVIEW

**Comment by hzoo** [comment]
Woah good idea! Maybe someone else can help review though @thejameskyle

**Comment by developit** [comment]
LGTM. It'd be nice to have SourceMap support, you can see a sortof hack for getting that done in [Preact's REPL](https://github.com/developit/preact-www/blob/master/src/components/controllers/repl/worker.js#L33-L39).

**Comment by bvaughn** [comment]
This is an old PR but I'm going to pick it up and run with it in the new REPL.

**Comment by bvaughn** [comment]
I've picked up this work over on PR #1346. Closing this PR for now since it's pretty stale.

Thanks a ton for kicking off this effort @boopathi !

**Pull request closed without merging**
