### PR TITLE
Added FusionCharts 🎉

### PR DESCRIPTION
**Pull request by shreyas-a**
thank you, BABEL 😄

### CODE REVIEW

**Comment by hzoo** [comment]
Deploy preview for *babel-new* ready!

Built with commit 3d16f82bbe1a9657bc13e37bbfba6d19722adcbd

https://deploy-preview-1596--babel-new.netlify.com

**Comment by xtuc** [comment]
Did you run your SVG through SVGO?

**Comment by existentialism** [comment]
@shreyas-a mind running svgo and adjusting viewbox to 500x200 so it doesn't appear so small?

image

thanks!

**Comment by existentialism** [comment]
@shreyas-a thanks!

**Comment by shreyas-a** [comment]
When can I expect the change in the **babel.io** website?

**Pull request merged**
