### PR TITLE
Add more Babel talks

### LINKED ISSUE #1767: Add some more Babel talks!
To https://github.com/babel/website/blob/master/website/data/videos.yml

Any others?

- https://www.youtube.com/watch?v=XvTsxa9i13o
- https://www.youtube.com/watch?v=9sPDcVYX3g8
- https://www.youtube.com/watch?v=h0sfFX7WH1c

### PR DESCRIPTION
**Pull request by thiagoarrais**
Closes #1767

I've tried to dig all the info from the video links. Please do revise.

### CODE REVIEW

**Comment by thiagoarrais** [comment]
Done.

**Comment by thiagoarrais** [comment]
Question: One of the videos has two authors, but the videos page assumes one author per video AFAIK. Would a new PR adding that be interesting?

**Comment by existentialism** [comment]
Yeah async loading the videos seem better, as well as fixing CSS layout (via flex or grid) so that things align properly should be good followups.

**Comment by thiagoarrais** [comment]
I have started working on a yml-based solution for multiple authors. Maybe I can port that to js? Can you link to the PR you mention so that I can have a look?

**Comment by thiagoarrais** [comment]
I have started working on a yml-based solution for multiple authors. Maybe I can port that to js? Can you link to the PR you mention, @hzoo, so that I can have a look?

**Comment by hzoo** [comment]
https://github.com/babel/website/pull/1834 this PR is way more since it basically is rewriting it, but like you can just convert the yml into JSON and then JS probably?

**Pull request merged**
