### PR TITLE
Add notice for stage presets deprecation

### PR DESCRIPTION
**Pull request by vikr01**
Since [the v7 migration docs mention the stage presets are deprecated](https://babeljs.io/docs/en/v7-migration#stage-preset-deprecations-https-githubcom-babel-babel-issues-7770), the pages for the stage presets should as well. I followed the format of the deprecation notices in the yearly preset docs.

I also went ahead and added links to [`@babel/preset-env`](https://babeljs.io/docs/en/babel-preset-env) in the yearly preset docs.

### CODE REVIEW

**Comment by vikr01** [comment]
[Example page from the deploy preview](https://deploy-preview-1859--babel.netlify.com/docs/en/babel-preset-stage-0#docsNav).

**Comment by existentialism** [comment]
Are the newly added 7.1.0 version of the preset-es* docs needed? It'll automatically fall back to the 7.0.0 docs.

**Comment by vikr01** [comment]
They seem to have been generated on precommit @existentialism, should I remove them?

**Comment by nicolo-ribaudo** [comment]
Maybe we should link to https://deploy-preview-1859--babel.netlify.com/blog/2018/07/27/removing-babels-stage-presets instead?

**Comment by vikr01** [comment]
@nicolo-ribaudo How about instead, I switch out the `(add link to blog post when published).` for that link on the `v7-migration`?

**Comment by vikr01** [comment]
That blog post isn't exactly something I'd show someone just looking for how to upgrade, and considering the v7-migration already links to it I'd say that should cover it. Though, I'll change it if that's what is believed to be better.

**Comment by nicolo-ribaudo** [comment]
> That blog post isn't exactly something I'd show someone who is just looking for how to upgrade

I think that "for more information" should point to something more than that short paragraph in the migration guide. But you are right, many people only want to know how to replace them: what about also linking the readmes? https://github.com/babel/babel/blob/master/packages/babel-preset-stage-0/README.md

**Comment by vikr01** [comment]
Done 👍

**Comment by existentialism** [comment]
Fine with landing this for now, but we should move the stage-0 readme info over to the website to be consistent with keeping everything here.

**Pull request merged**
