### PR TITLE
fix(externalPlugins): make sure the input is focusing correctly in Safari (old site)

### PR DESCRIPTION
**Pull request by Haroenv**
same as #1612

### CODE REVIEW

**Comment by hzoo** [comment]
Deploy preview for *babel-old* ready!

Built with commit 716e5c7c84cd704782860f51aebb3e10ed9f9fe8

https://deploy-preview-1613--babel-old.netlify.com

**Comment by Haroenv** [comment]
works as expected 🙌

**Comment by existentialism** [comment]
@Haroenv thanks!

**Comment by Haroenv** [comment]
With pleasure!

**Pull request merged**
