### PR TITLE
Added drag and drop file ability on REPL

### PR DESCRIPTION
**Pull request by ericponto**

### CODE REVIEW

**Comment by thejameskyle** [comment]
We should put some text somewhere that you can do this

**Comment by sebmck** [comment]
We probably need a help modal.

**Comment by ericponto** [comment]
There's probably some room in the black options bar to put a little note.

**Comment by ericponto** [comment]
I'd have time to update this tonight if there is anything specific you'd like in terms of adding a description or help text.

**Comment by ericponto** [comment]
@sebmck I can create a help modal...if you can help provide some content for it. My other thought was a one time alert that could use localstorage to track if a user has seen it.

**Comment by ericponto** [comment]
I added upload and download buttons to the REPL to add to the drag and drop functionality.

**Comment by sebmck** [comment]
:+1: Looks good to me! Sorry for the delay, what do you think @thejameskyle?

**Comment by ericponto** [comment]
Hey @thejameskyle. Selfishly I'd like to see this merged as it's something I'd use. Anything else you'd like me to do?

**Comment by ericponto** [comment]
Just revisiting my code, I do probably need a fallback on the download for IE and Safari. I can code that up tonight.

**Comment by ericponto** [comment]
I decided just to hide the download button. If you want to support more browsers there are some file saving libraries that we could add, but I wasn't sure it you'd want to add that dependency for this feature.

**Comment by sebmck** [comment]
Ping @thejameskyle. Sorry @ericponto that his has taken so long.

**Comment by ericponto** [comment]
With the new checkbox for execute, does another spot for the upload button make more sense? 

Is this a feature you are still interested in?

**Comment by piecioshka** [comment]
:+1: nice feature

**Comment by thejameskyle** [comment]
@piecioshka Please stop making +1 comments on GitHub, I delete all of them as they are noisy and annoying.

**Comment by piecioshka** [comment]
@thejameskyle sorry James. I like "+1" I see because that a particular feature (for which a vote) is then popular.

Sometimes it is indeed "noisy", but one or two commnets with "+1" are not so bad.

More smile :smile:

**Comment by hzoo** [comment]
we still want this?

**Comment by ericponto** [comment]
I'm willing to relook at it and update the PR if things have changed.

**Comment by ericponto** [comment]
@hzoo - I went ahead and resolved the merge conflict and got this up to date with the current version of the REPL page. (Not too much work considering I have touched this in a couple of years 😄 ).

**Comment by ericponto** [comment]
This is probably out of date with the new REPL. I can submit a new PR to add this feature to the new REPL if it is still wanted.

**Comment by ericponto** [comment]
The same functionality has been added to the rewritten REPL in PR #1344.

**Pull request closed without merging**
