### PR TITLE
Update to Prettier 1.13

### PR DESCRIPTION
**Pull request by duailibe**
I had to tweak the plugin loading a bit because of how Prettier works in the browser now :)

### CODE REVIEW

**Comment by hzoo** [comment]
Deploy preview for *babel-new* ready!

Built with commit 91a8ba48442740bc7c4e082561d4c7a96e2944a8

https://deploy-preview-1672--babel-new.netlify.com

**Comment by hzoo** [comment]
Deploy preview for *babel-new* ready!

Built with commit 99356226723a74685d3565d22ba8942da0f79059

https://deploy-preview-1672--babel-new.netlify.com

**Comment by duailibe** [comment]
I considered that as I was typing random stuff to test this.. but I figured that should be a button "Prettify input" rather than automatically? Not sure how that UX would be

**Comment by existentialism** [comment]
@duailibe thanks!

**Pull request merged**
