### PR TITLE
Update parser.md

### PR DESCRIPTION
**Pull request by chenxsan**
Thought it's a typo there.

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Is it possible to make it work both in markdown and on the website? Maybe by using `<code>` instead of backticks?

**Comment by chenxsan** [comment]
@nicolo-ribaudo Maybe escape `|` with a `\`?

It looks fine in my test.

Code:
```
| Name | Code Example |
|------|--------------|
| `pipelineOperator` ([proposal](https://github.com/babel/proposals/issues/29)) | `a \|> b` |
| `throwExpressions` ([proposal](https://github.com/babel/proposals/issues/23)) | `() => throw new Error("")` |
```
Rendered:

| Name | Code Example |
|------|--------------|
| `pipelineOperator` ([proposal](https://github.com/babel/proposals/issues/29)) | `a \|> b` |
| `throwExpressions` ([proposal](https://github.com/babel/proposals/issues/23)) | `() => throw new Error("")` |

**Comment by nicolo-ribaudo** [comment]
I still see the HTML entity in the site preview 🤔

**Comment by chenxsan** [comment]
@nicolo-ribaudo Tried `<code></code>`, looks fine now:

image

Not sure what's going on with the `website/versioned_docs/version-7.1.0/parser.md` file, seems it's auto generated when I commit.

**Pull request merged**
