### PR TITLE
update landing page examples

### PR DESCRIPTION
**Pull request by JLHwung**
Closes https://github.com/babel/website/issues/2551

### CODE REVIEW

**Comment by liuxingbaoyu** [comment]
These few examples don't look very good.
The output of the decorator is very, very long and completely unreadable.
The pipeline-operator is not that famous.
record-and-tuple relies entirely on polyfills.

Unfortunately I didn't think of a good example either.

**Comment by JLHwung** [comment]
I have removed decorators and pipeline examples. The new examples are from ES2025 and stage 3 explicit-resource-management proposal. Please take a look.

**Review by liuxingbaoyu — APPROVED** [review]
Thanks!
Non-blocking: Would `proposal-throw-expressions` be better than `proposal-do-expressions`?

**Comment by JLHwung** [comment]
I am fine with either proposal, as long as we showcase something still in early stage. That said, I have updated the examples for throw expressions.

**Pull request merged**
