### PR TITLE
babel-plugin-check-es2015-constants 翻译

### PR DESCRIPTION
**Pull request by Xiaoxianrou**
翻译完成

### CODE REVIEW

**Comment by hzoo** [comment]
Hmm I think we need to setup crowdin or some translation service (we aren't going to be merging into master at least)

**Comment by Xiaoxianrou** [comment]
Sorry guys,

**Comment by Xiaoxianrou** [comment]
Sorry guys, I pull request the wrong place. so sorry

**Comment by existentialism** [comment]
@Xiaoxianrou no worries, we should work together on getting the READMEs and the rest of the site translated together!

**Comment by xtuc** [comment]
Yes, I believe it's already (almost everywhere) the case.

**Pull request closed without merging**
