### PR TITLE
Fix typos in both @babel/plugin-proposal-export-*-from packages

### PR DESCRIPTION
**Pull request by kevinSuttle**
https://github.com/babel/babel/blob/v7.0.0-beta.46/packages/babel-plugin-proposal-export-default-from/package.json#L2
https://github.com/babel/babel/blob/v7.0.0-beta.46/packages/babel-plugin-proposal-export-namespace-from/package.json#L2

### CODE REVIEW

**Comment by hzoo** [comment]
Deploy preview for *babel-new* ready!

Built with commit ac3ace7231800e837eba7d1e17e6f71d2d0a099d

https://deploy-preview-1645--babel-new.netlify.com

**Comment by kevinSuttle** [comment]
Looks good https://deploy-preview-1645--babel-new.netlify.com/docs/en/next/v7-migration.html#split-babel-plugin-transform-export-extensions-into-the-two-renamed-proposals

**Comment by existentialism** [comment]
@kevinSuttle thanks!

**Comment by kevinSuttle** [comment]
My pleasure!

**Comment by hzoo** [comment]
Awesome, are yall updating now?

**Pull request merged**
