### PR TITLE
Update plugins.md

### PR DESCRIPTION
**Pull request by Ore4444**
added link to typescript transform

### CODE REVIEW

**Comment by Ore4444** [comment]
* `preset-typescript` is not listed on this page
* presets in general are not listed on this page
* this page lists transform plugins and `plugin-transform-typescript` is one.

**Comment by hzoo** [comment]
We do have a separate presets page which is linked to at the top and it does link to the typescript preset if that helps

**Comment by xtuc** [comment]
Sorry I didn't realize that this page only list plugins, I don't really mind adding this but i'm just worried that it doesn't really help the user and might confuse them.

**Comment by hzoo** [comment]
Yeah I think we don't really want the user to use the plugin directly anyway that's all

**Comment by Ore4444** [comment]
Yes, but the preset-typescript page doesn't include (or link to) important info like which TS features are not supported by Babel.

**Comment by hzoo** [comment]
ok sure, i noticed we put the flow one there anyway

**Pull request merged**
