### PR TITLE
Added doc for --copy-ignored flag

### PR DESCRIPTION
**Pull request by rajasekarm**
Documented --copy-ignored (https://github.com/babel/babel/pull/10887/) in options section as per @existentialism  comment.

https://github.com/babel/website/pull/2146#discussion_r358862858

### CODE REVIEW

**Comment by JLHwung** [comment]
We do have a dedicated `babel-cli` docs, can you move it to `docs/cli.md`?

**Comment by rajasekarm** [comment]
@JLHwung I moved here as per @existentialism comment. https://github.com/babel/website/pull/2146#discussion_r358862858

**Comment by JLHwung** [comment]
Ah I see, the advanced section of cli.md refers to this page. I feel it’s more natural if we move cli options before option concepts, same as options falling into other categories.

**Comment by rajasekarm** [comment]
@JLHwung Done

**Pull request merged**
