### PR TITLE
Fix highlighted menu item

### LINKED ISSUE #1324: "Try it out" menubar item should be selected when on new REPL
https://babeljs.io/repl/ -> "Try it out" is selected.
https://babeljs.io/repl-old/ -> "Try it out" is not selected.
https://babeljs.io/php -> "Try it out" is not selected.

### PR DESCRIPTION
**Pull request by zanonnicola**
I couldn't find a CSS only way to do this on Docusaurus so I added a little script that check the `path` and add an active class to the menu item.

Let me know what you guys think.

Fix #1324 (on the new site)

### CODE REVIEW

**Comment by hzoo** [comment]
Deploy preview for *babel-new* ready!

Built with commit 36cf908846d8687ac7f0b4076d2d3a3801d1b981

https://deploy-preview-1580--babel-new.netlify.com

**Comment by existentialism** [comment]
Maybe we should get this fixed upstream in Docusarus?

Ref: https://github.com/facebook/Docusaurus/issues/178

**Comment by hzoo** [comment]
Yeah can ping @JoelMarcey

**Comment by zanonnicola** [comment]
Agree, makes sense anyway.

**Comment by zanonnicola** [comment]
@hzoo @existentialism @joelmarcy I opened an issue in Docusaurus: https://github.com/facebook/Docusaurus/issues/456

We can go with a JS solution for now or wait until we have a better way to handle this. Up to you!

**Comment by hzoo** [comment]
This should be fixed by https://github.com/facebook/Docusaurus/commit/48ee457ec98b728343196362d5d42c0dc3d1cff9 now? @joelmarcey @microbouji

**Comment by JoelMarcey** [comment]
@hzoo Yep. This should be resolved in v1.0.9.

**Comment by JoelMarcey** [comment]
e.g., if you go here: https://docusaurus.io/docs/en/installation.html you can see that `Docs` is highlighted in the header.

See https://github.com/facebook/Docusaurus/pull/463

**Comment by microbouji** [comment]
yeah we can do this with css only now from our side. Active items get `siteNavItemActive` class when exact match, and `siteNavGroupActive` when currently displayed page is part of the same sidebar as the nav item.

**Comment by existentialism** [comment]
Awesome! Works great:
https://deploy-preview-1603--babel-new.netlify.com/docs/en/index.html

**Comment by microbouji** [comment]
It only needs those those :active and :focus styles now from 399efae

**Pull request closed without merging**
