### PR TITLE
Modernize examples for plugin-transform-react-jsx

### PR DESCRIPTION
**Pull request by loklaan**
👋

I think the code examples for `@babel/plugin-transform-react-jsx` could benefit from a small update, to keep them relevant!

* `deku` → `@emotion/core`
* es5 + cjs → esnext + esm

Let me know if this change would be undesirable, cheers!

### CODE REVIEW

**Comment by suchipi** [comment]
I actually like that the `/* @jsx dom */` makes it clear that the thing after the pragma is a variable name. I don't think that is as clear with `/* @jsx jsx */`. Could we keep it using deku? Or maybe hyperscript or something else whose element constructor is not `jsx`?

**Comment by loklaan** [comment]
Oh yeah, good point!

I'll swap out the `@emotion/core` → `preact` (which also has a custom `Fragment` jsxFrag to use 👌)

**Comment by suchipi** [comment]
Perfect, thanks!

**Comment by suchipi** [comment]
Nice to get a real fragment thing in there, too :)

**Pull request merged**
