### PR TITLE
fix preset-minify plugins links

### PR DESCRIPTION
**Pull request by Simek**
Fix links (404) on preset-minify page: https://babeljs.io/docs/en/babel-preset-minify

### CODE REVIEW

**Comment by hzoo** [comment]
Thanks for the PR! Is it just me or the url don't seem to work here? https://deploy-preview-1734--babel.netlify.com/docs/en/babel-preset-minify

**Comment by JoelMarcey** [comment]
@hzoo That Netlify link worked for me.

**Comment by existentialism** [comment]
The links on that page 404 for me too

**Comment by JoelMarcey** [comment]
@existentialism What is 404ing? - The Netlify link works and I clicked on various links on the page and they seem to work. Is there a specific link on the Netlify page that is 404'ing?

**Comment by existentialism** [comment]
@JoelMarcey these:

image

**Comment by Simek** [comment]
@existentialism The page you mentioned should be fine now. @microbouji pointed out that 6.x page should also be updated.

**Comment by existentialism** [comment]
Lol, ok that makes sense.

I was confused b/c the original comment mentioned `/docs/en/babel-preset-minify`, so that's the URL I checked :)

**Comment by existentialism** [comment]
@Simek thanks!

**Pull request merged**
